name: flutter_ddd_todos
description: A new Flutter application.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.2
  freezed_annotation: ^0.12.0
  cupertino_icons: ^1.0.0
  flutter_bloc: ^6.0.6
  # firebase
  firebase_core: ^0.5.1
  firebase_auth: ^0.18.2
  google_sign_in: ^4.5.5
  # dependency injection
  get_it: ^5.0.1
  injectable: ^1.0.5
  # UI
  flushbar: ^1.10.4
  # Tools
  uuid: ^2.2.2

dev_dependencies:
  freezed: ^0.12.2
  lint: ^1.3.0
  injectable_generator: ^1.0.6
  # build
  build_runner: ^1.10.4
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
