name: flutter_ddd_todos
description: A new Flutter application.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.2
  freezed_annotation: ^0.12.0
  cupertino_icons: ^1.0.0
  flutter_bloc: ^6.0.6

dev_dependencies:
  freezed: ^0.12.1
  build_runner: ^1.10.2
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
