name: flutter_ddd_todos
description: A new Flutter application.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^6.1.1
  # firebase
  cloud_firestore: ^0.16.0
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  google_sign_in: ^4.5.9
  # UI
  flushbar: ^1.10.4
  cupertino_icons: ^1.0.0
  # Tools
  uuid: ^2.2.2
  json_annotation: ^3.1.1
  flutter_hooks: ^0.15.0
  provider: ^4.3.3
  # Auto-gen
  freezed_annotation: ^0.12.0
  get_it: ^5.0.6
  injectable: ^1.0.7
  auto_route: ^0.6.9
  # Functional programming
  dartz: ^0.9.2
  kt_dart: ^0.8.0
  rxdart: ^0.25.0



dev_dependencies:
  lint: ^1.3.1
  # Auto-gen
  freezed: ^0.12.7
  injectable_generator: ^1.0.7
  auto_route_generator: ^0.6.10
  json_serializable: ^3.5.1
  # build
  build_runner: ^1.11.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
