name: flutter_ddd_todos
description: A new Flutter application.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.2

  cupertino_icons: ^1.0.0
  flutter_bloc: ^6.0.6
  # firebase
  firebase_core: ^0.5.1
  firebase_auth: ^0.18.2
  google_sign_in: ^4.5.6
  # UI
  flushbar: ^1.10.4
  # Tools
  uuid: ^2.2.2
  # Auto-gen
  freezed_annotation: ^0.12.0
  get_it: ^5.0.1
  injectable: ^1.0.5
  auto_route: ^0.6.9


dev_dependencies:
  lint: ^1.3.0
  # Auto-gen
  injectable_generator: ^1.0.6
  freezed: ^0.12.2
  auto_route_generator: ^0.6.10
  # build
  build_runner: ^1.10.4
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
